name: 'ecommerce'
version: '1.0.0'

profile: 'ecommerce'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce:

    staging:
      +materialized: view
      +schema: STAGING

    intermediate:
      +materialized: view
      +schema: STAGING

    marts:
      +materialized: table
      +schema: ANALYTICS

